---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deploy load-balancer configuration
  template:
    src: lb-nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - Restart nginx
